version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: production_nginx
    volumes:
      - ./nginx:/etc/nginx/
    ports:
      - 80:80
      - 443:443

  grey_whale:
    image: nginx:stable-alpine
    container_name: grey_whale
    volumes:
      - ./grey_whale/conf:/etc/nginx
      - ./grey_whale/html:/usr/share/nginx/html
    ports:
      - 7000:80

  blue_whale:
    image: nginx:stable-alpine
    container_name: blue_whale
    volumes:
      - ./blue_whale/conf:/etc/nginx
      - ./blue_whale/html:/usr/share/nginx/html
    ports:
      - 8000:80

  green_whale:
    image: nginx:stable-alpine
    container_name: green_whale
    volumes:
      - ./green_whale/conf:/etc/nginx
      - ./green_whale/html:/usr/share/nginx/html
    ports:
      - 9000:80
